ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        host: 0.0.0.0
        port: 8080
jwt:
  domain: ${DOMAIN}
  audience: ${JWT_AUDIENCE}
  realm: ${JWT_REALM}
  secret: ${JWT_SECRET}